# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Описание фото')),
                ('slug', models.SlugField(max_length=200)),
                ('file', models.FileField(blank=True, max_length=180, upload_to='uploads/%Y/%m/%d', verbose_name='Изображение к посту')),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('seo_alt', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file_preview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_landing.Images')),
            ],
            options={
                'verbose_name_plural': 'Фотографии постов',
                'verbose_name': 'Фотография поста',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название раздела')),
                ('slug', models.SlugField(max_length=200)),
                ('text_post', models.TextField(blank=True, verbose_name='Описание сервиса')),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('index', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_post', models.ManyToManyField(to='app_landing.Images')),
            ],
            options={
                'verbose_name_plural': 'Название сервисов',
                'db_table': 'post_table',
                'verbose_name': 'Название сервиса',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Наименование пакета')),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(verbose_name='Описание пакета услуг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена пакета')),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Название пакетов услуг',
                'verbose_name': 'Название пакета услуг',
            },
        ),
    ]
