# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0002_auto_20161031_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_landing.Images'),
        ),
    ]
