# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0003_auto_20161031_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ManyToManyField(blank=True, to='app_landing.Images'),
        ),
    ]
