# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0004_auto_20161031_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
