# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0005_auto_20161031_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icons',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
