# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0007_auto_20161031_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_support', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app_landing.Post')),
            ],
        ),
    ]
