# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0008_subpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='icons',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='post_support',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поддержка сервиса'),
        ),
    ]
