# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0009_auto_20161101_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
