# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0010_price_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Сервис')),
                ('slug', models.SlugField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Описание сервиса')),
                ('icons', models.CharField(blank=True, max_length=20, verbose_name='Иконка')),
                ('index', models.PositiveSmallIntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_service', models.ManyToManyField(blank=True, to='app_landing.Images', verbose_name='Фото сервиса')),
                ('label', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_services', to='app_landing.Label')),
            ],
            options={
                'ordering': ['index'],
                'verbose_name_plural': 'Сервисы',
                'verbose_name': 'Сервис',
                'db_table': 'app_services',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['index'], 'verbose_name': 'Название поста', 'verbose_name_plural': 'Название постов'},
        ),
        migrations.AddField(
            model_name='services',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_service', to='app_landing.Post'),
        ),
    ]
