# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0011_auto_20161101_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ManyToManyField(related_name='background', to='app_landing.Images')),
            ],
        ),
    ]
