# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing', '0012_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Контакты')),
                ('description', models.CharField(blank=True, max_length=1200, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, max_length=120, verbose_name='e-mail')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
